# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blurb', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeStaffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Mx.', 'Mx.'), ('Dr.', 'Dr.')], max_length=4)),
                ('suffix', models.CharField(blank=True, max_length=16)),
                ('role', models.CharField(choices=[('Chair', 'Chair'), ('Moderator', 'Moderator'), ('Staffer', 'Staffer'), ('Crisis Director', 'Crisis Director')], max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffers', to='atlas.Committee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Mx.', 'Mx.'), ('Dr.', 'Dr.')], max_length=4)),
                ('suffix', models.CharField(blank=True, max_length=16)),
                ('role', models.CharField(choices=[('SecGen', 'Secretary General'), ('COO', 'Chief Operating Officer'), ('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technical Officer'), ('CAO', 'Chief Administrative Officer'), ('COS', 'Chief of Staff'), ('MAL', 'Member at Large'), ('USG', 'Under-Secretary-General')], max_length=8)),
                ('blurb', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USGGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=8, unique=True)),
                ('blurb', models.TextField(blank=True)),
                ('usg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usg_group', to='atlas.InternalUser')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='delegations',
            field=models.ManyToManyField(blank=True, related_name='committees', to='atlas.Delegation'),
        ),
        migrations.AddField(
            model_name='committee',
            name='usg_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='atlas.USGGroup'),
        ),
    ]
