# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('munuc_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='USGGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='grant_financial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='committee',
            name='usg_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munuc_api.USGGroup'),
        ),
    ]
