# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munuc_api', '0002_auto_20160922_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='abbreviation',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usggroup',
            name='abbreviation',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
