# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('munuc_api', '0003_auto_20160922_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='blurb',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usggroup',
            name='blurb',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='committee',
            name='usg_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='munuc_api.USGGroup'),
        ),
    ]
