# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munuc_api', '0004_auto_20160922_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('committees', models.ManyToManyField(to='munuc_api.Committee')),
            ],
        ),
    ]
