# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munuc_api', '0006_auto_20160922_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
