# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munuc_api', '0007_auto_20160922_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='countries',
            field=models.ManyToManyField(related_name='committees', to='munuc_api.Country'),
        ),
    ]
